workspace:
  base: /go
  path: src/github.com/tanus-co/snowflake

pipeline:
  build:
    image: golang:1.12.5
    commands:
      - go mod download
      - go build

trigger:
  branch:
    - develop
  event:
    - push
    - merge