workspace:
  base: /src
  path: github.com/tanus-co/snowflake

pipeline:
  build:
    image: golang:1.12.5
    commands:
      - GO111MODULE=on
      - go mod download
      - go build

trigger:
  branch:
    - develop
    - feature/*
  event:
    - push
    - merge